version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file: ./.env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: